version: '2.1'

services:
    nodejs-app:
        image: satvickkoneru/mydomain:latest
        container_name: mydomain
        hostname: mydomain
        ports:
            - "8888:8888" 
        networks:
            - example-net  
    nginx:
        image: satvickkoneru/nginx:latest
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejs-app
        networks:
            - example-net
    Elasticsearch:
        image: elasticsearch:7.16.2
        container_name: elasticsearch
        restart: always
        volumes:
               - elastic_data:/usr/share/elasticsearch/data/
        environment:
           ES_JAVA_OPTS: "-Xmx256m -Xms256m"
           discovery.type: single-node    
        ports:
               - '9200:9200'
               - '9300:9300' 
        networks:
               - example-net

    Logstash:
        image: logstash:7.16.2
        container_name: logstash
        restart: always
        volumes:
                - ./logstash/:/logstash_dir
        command: logstash -f /logstash_dir/logstash.conf 
        depends_on:
                 - Elasticsearch
        ports:
                 - '9600:9600'
        environment:
           LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
        networks:
               - example-net

    Kibana:
        image: kibana:7.16.2
        container_name: kibana
        restart: always       
        ports:
          - '5601:5601'
        environment:
          - ELASTICSEARCH_URL=http://elasticsearch:9200  
        depends_on:
          - Elasticsearch  
        networks:
          - example-net
volumes:
  elastic_data: {}
networks:
 example-net:
  external: true

